assemblyDir="/share/home/zhanglab/user/sunyanqing/human/assembly/"
MonomerT2Tdb="./MonomerT2TDB/MonomerT2T.consensus"
MonomerGlobaldb="./MonomerGlobalDB/MonomerGlobalDB"
hsat23pl="./Scripts/Assembly_HSat2and3_v3.pl"
hsat2db="./Scripts/HSat2_kmers.txt"
hsat3db="./Scripts/HSat3_kmers.txt"
hsat1py="./Scripts/Assembly_HSat1.py"
barplotpy="./Scripts/barplot.py"
bedtools="/share/home/zhanglab/user/sunyanqing/miniconda3/bin/bedtools"
samtools="/share/home/zhanglab/user/sunyanqing/miniconda3/envs/viz/bin/samtools"
repeatmasker="/share/home/zhanglab/user/sunyanqing/software/RepeatMasker/RepeatMasker"
mergesatpy="./Scripts/merge_satellite.py"
